### ISSUE TITLE
[CRF General Bug] Issue with dropping wounded person during CFC

### ISSUE THREAD

**Issue by GHPCee** [CoalitionArma/Coalition-Reforger-Framework#108] opened 2024-06-03 22:09 UTC
**Describe the bug**
Was unable to drop body of unconscious player after picking their body up. This happened after I reconnected to server during game start after server kicked me and "JIP"-ed back onto my body that was controlled by AI.

**To Reproduce**
1. Reconnect to server after you already spawned in a slot.
2. Try to pick up and drop unconscious player body. 

**Expected behavior**
Body not being removed from player's shoulder after tapping 'ctrl+x' many times over. Tried to change keybinds and try again as well many times.

**Device (please complete the following information):**
- Type: PC

**Comment by tanaaKa** [comment] 2024-06-03 23:09
Should most likely be transferred to the ace anvil wiki.
https://github.com/acemod/ACE-Anvil

**Comment by Njpatman** [comment] 2024-06-04 05:20
> Should most likely be transferred to the ace anvil wiki. https://github.com/acemod/ACE-Anvil

^ This, we will not fix other people's mods for them in the CRF. It could also be caused by Reforger Lobby :

https://github.com/JiraF4/PlayableSelector

I'd make a bug report on both repos, but note that the ACE Team will prob differ you to the lobby team as lobby does use its own system for jips/reconnects.

**Closed as completed by Njpatman** 2024-06-04 05:20 UTC
